manipulator:
  kinematics_solver: moveit_opw_kinematics_plugin/MoveItOPWKinematicsPlugin
  opw_kinematics_geometric_parameters:
      a1:  0.0
      a2:  0.0
      b:   0.0345
      c1:  0.1525
      c2:  0.62
      c3:  0.559
      c4:  0.121
  opw_kinematics_joint_offsets: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  opw_kinematics_joint_sign_corrections: [1, 1, 1, 1, 1, 1]
